# golangci-lint configuration v2
version: "2"

run:
  tests: false
  timeout: 2m

formatters:
  enable:
    - gci
    - gofmt
    - goimports

linters:
  default: standard
  enable:
    - bodyclose
    - staticcheck  # replaces megacheck
    - unused       # replaces megacheck
    - govet
    - unconvert
    - gosec        # replaces gas
    - gocyclo
    - dupl
    - misspell
    - unparam
    - ineffassign
    - gochecknoinits
    - gocritic
    - nakedret
    - prealloc
    - errcheck
    - govet
  settings:
    goconst:
      min-len: 2
      min-occurrences: 2
    misspell:
      locale: US
    lll:
      line-length: 140
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
  exclusions:
    rules:
      - text: 'shadow: declaration of "(err|ctx)" shadows declaration at'
        linters: [ govet ]
